### ISSUE TITLE
allow users of Document to provide their own self link

### ISSUE THREAD

**Issue by jcjones1515** [thisissoon/Flask-HAL#27]
I've run into some cases where I want to provide a self link that does not match the currently request URL.  For example, is someone is POSTing to one URI to create a new resource, but the self link for that new resource returned is actually a different URI.  

Today Flask-HAL will put a self link in for the current URI and I have to strip it out and add my own.

I'm willing to add this to the code, but wanted to get some thoughts on approaches:

1.  When creating a ```Document``` if you provide a ```self``` link it will not add it's own self link
2.  provide an explicit ```self_uri``` argument to the constructor that will be used instead of the default self link
3. ???

I tend to favor the first approach, but I could see it leading to unexpected behavior for those not aware of the ability to override it in that way.

**Comment by jcjones1515** [comment]
@krak3n, was hoping I could get your thoughts on this before starting any code on it

**Comment by krak3n** [comment]
@jcjones1515 from my understanding of the spec is when issuing a `POST` request to create a new resource the response body should look like this:

``` http
HTTP/1.1 201 CREATED
Content-Type: application/json

{
    "_links": {
        "self": { 
            "href": "/orders" 
        },
        "created": { 
            "href": "/orders/1" 
        }
    }
}
```

I think `self` should always be the resource our are on.

Having said that, I'm not averse to overriding `self` for occasions that might require it, I would probably prefer optional keyword arg you could pass into `Document`.

**Comment by jcjones1515** [comment]
thanks, @krak3n -- we talked about it a little bit and what we were trying to do is provide the created resource inline in the response to prevent the roundtrip, but I think we are in agreement that the ```self``` link not matching the resource being ```POST```ed too is wrong.

I think we're going to go with an alternate approach.  I'll go ahead and close this issue.  Thanks.
